name: API CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  api-test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Verify Newman installation
        run: newman -v

      - name: Run Postman API tests
        run: |
          newman run S2O-Test-full-api.postman_collection.json \
          -e "S2O.postman_environment (1).json" \
          --reporters cli
